---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner-smb
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-smb-cluster-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: ["samba-operator.samba.org"]
    resources: ["smbshare"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-smb-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: csi-provisioner-smb
    namespace: samba-operator-system
roleRef:
  kind: ClusterRole
  name: csi-provisioner-smb-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-smb-role
rules:
  - apiGroups: ["samba-operator.samba.org"]
    resources: ["smbshare"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-smb-role-binding
subjects:
  - kind: ServiceAccount
    name: csi-provisioner-smb
    namespace: samba-operator-system
roleRef:
  kind: Role
  name: csi-provisioner-smb-role
  apiGroup: rbac.authorization.k8s.io
